### PR TITLE
Uplift Kakao deps to 3.0.0 with new groupId

### PR DESCRIPTION
**Pull request by Vacxe**
Agoda's repository is no longer supported. New version has been deployed to maven repo. Unfortunately it require package update.
Ref: https://github.com/KakaoCup/Kakao

### CODE REVIEW

**Comment by Vacxe** [comment]
Wait for 3.0.1 do not merge

**Comment by Vacxe** [comment]
Dependency has been updated to 3.0.1. Checks can be executed when maven central will be synchronised about ~6h

**Comment by RuslanMingaliev** [comment]
> Wait for 3.0.1 do not merge

We use the [WIP](https://github.com/wip/app) bot for such purposes. Just add a `[WIP]` prefix to the title next time :) 

Also, I think we need a simple script or a Gradle task to help end-users migrate.

**Comment by Vacxe** [comment]
@RuslanMingaliev ready to merge

**Review by RuslanMingaliev — APPROVED** [review]

**Review by matzuk — APPROVED** [review]

**Pull request merged**
